services:
  daris-database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: somosdaris
    ports:
      - "5432:5432"
    volumes:
      - daris-data:/var/lib/postgresql/data
volumes:
  daris-data: